POST http://localhost:8080/events
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzM3Njk1MTYyLCJ1c2VySWQiOjF9.vriZbfxSVuEFir6tqrjFHyoDRKtS__ARfob_7GQw2Zg


{
    "name": "Event 1",
    "description": "This is event 1",
    "location":"kampala",
    "dateTime": "2024-03-16T14:30:00.000Z"

}

